const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const root = path.join(__dirname,'..');
const crt=fs.readFileSync(path.join(root,'js/crt.js'),'utf8');
const helper=crt.match(/function mediaFileKind\(file\) \{[\s\S]*?\n\}/);
assert.ok(helper,'File picker and drop must share media validation');
const ctx=vm.createContext({});vm.runInContext(helper[0],ctx);
for(const [file,kind]of [[{type:'image/png',name:'sample.png'},'image'],[{type:'video/mp4',name:'sample.mp4'},'video'],[{type:'',name:'MOVIE.WEBM'},'video'],[{type:'',name:'photo.jpeg'},'image'],[{type:'text/html',name:'fake.png'},null],[{type:'application/pdf',name:'doc.pdf'},null],[null,null]])assert.equal(ctx.mediaFileKind(file),kind);
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
assert.ok(html.includes('id="mediaDropHint"'));
assert.ok(crt.includes('function loadMediaFile(file)'));
const source=fs.readFileSync(path.join(root,'js/controls.js'),'utf8');
const binding=source.match(/function initializeMediaDrop\(\) \{[\s\S]*?\n\}/);
assert.ok(binding,'Native file drop handler is present');
const handlers={},loads=[],messages=[],classes=new Set();
const machine={classList:{add:key=>classes.add(key),remove:key=>classes.delete(key)}};
Object.assign(ctx,{document:{querySelector:()=>machine,getElementById:()=>({value:''}),addEventListener:(name,fn)=>handlers[name]=fn},window:{addEventListener(){}},loadMediaFile:file=>loads.push(file),setMediaImportStatus:text=>messages.push(text)});
vm.runInContext(binding[0]+'\ninitializeMediaDrop();',ctx);
const image={type:'image/png',name:'sample.png'};
function event(files,types=['Files']) {return {dataTransfer:{files,types},preventDefault(){this.prevented=true;},relatedTarget:null};}
const over=event([image]);handlers.dragover(over);assert.ok(over.prevented);assert.ok(classes.has('media-dragover'));
handlers.drop(event([image]));assert.equal(loads[0],image);assert.ok(!classes.has('media-dragover'));
handlers.drop(event([image,image]));assert.equal(loads.length,1,'Reject multiple files without replacing current media');
handlers.drop(event([{type:'text/plain',name:'notes.txt'}]));assert.equal(loads.length,1);
const url=event([],['text/uri-list']);handlers.dragover(url);assert.ok(!url.prevented,'Do not intercept non-file drags');
assert.equal(messages.length,2);
console.log('Media drop validation, highlight, single-file routing and rejection checks passed');
